spring:
  main:
    banner-mode: off
  data:
    redis:
      host: auth-service-db
logging:
  level:
    root: warn
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

