spring:
  datasource:
    url: jdbc:postgresql://event-service-db:5432/event
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
