spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/event
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
