spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service-route
              predicates:
                - Path=/api/users/**, /api/roles/**
              uri: lb://USER-SERVICE

            - id: auth-service-route
              predicates:
                - Path=/api/auth/**
              uri: lb://AUTH-SERVICE
              
            - id: event-service-route
              predicates:
                - Path=/api/event/**
              uri: lb://EVENT-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
