spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service-route
              predicates:
                - Path=/api/users/**, /api/roles/**
              uri: lb://USER-SERVICE
              filters:
                - Authentication
    
            - id: auth-service-route
              predicates:
                - Path=/api/auth/**
              uri: lb://AUTH-SERVICE
    
            - id: event-service-route
              predicates:
                - Path=/api/events/**
              uri: lb://EVENT-SERVICE
              filters:
                - Authentication
              
           - id: ticket-service-route
              predicates:
                - Path=/api/tickets/**
              uri: lb://TICKET-SERVICE
              filters:
                - Authentication

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
