spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service-route
              predicates:
                - Path=/api/users/**, /api/roles/**
              uri: lb://USER-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
logging:
  level:
    root: warn
