spring:
  datasource:
    url: jdbc:postgresql://ticket-service-db:5432/ticket
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    rabbitmq:
      host: rabbitmq 
      port: 15672
      username: guest
      password: guest
  sql:
    init:
      mode: always
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
