spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/ticket
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    rabbitmq:
      host: localhost 
      port: 15672
      username: guest
      password: guest
  sql:
    init:
      mode: always
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
