spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5433/user
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
logging:
  level:
    root: warn
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
