spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://user-service-db:5432/user
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
logging:
  level:
    root: warn
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  prefer-ip-address: false
  hostname: localhost
